
name: Exemplo Input
run-name: Exemplo workflow para input, executado por ${{ github.actor }}
on: 
    workflow_dispatch:
        inputs:
            versao:
              type: string
              required: true 
              default: "dev"
              description: "Versão da nova release"
            numero_card:
              type: number
              required: true
              description: "Numero do card da tarefa desse commit"
            fazer_depoy:
              type: boolean
              required: true
              description: "Especifica se deve ou não fazewe deploy"
            ambiente:
              type: choice
              required: true
              description: "Ambiente Deploy"
              options:
                - Desenvolvimento
                - Homologação
                - Produção
jobs:
    valores_input:
      runs-on: ubuntu-latest
      steps:
        - name: Exibindo o contexto de input completo
          run: echo "${{ toJson(inputs)}}"
        - name: Exibindo os valores passados nos inputs
          run:
              echo "Esses são os valores passados nos inputs"
              echo "A Versão é ${{ inputs.versão }}"
              echo "O card é ${{ inputs.numero_card }}"
              echo "Deve fazer deploy ${{ inputs.fazer_deploy }}"
              echo "O ambiente ${{ inputs.ambiente }}"
